# Closed-World UI Theme Definition
# This file defines appearance while developers define structure.
# Future: This will compile to CSS. For now, CSS is written manually to match.

tokens:
  spacing:
    1: 0.25rem    # 4px
    2: 0.5rem     # 8px
    3: 0.75rem    # 12px
    4: 1rem       # 16px
    5: 1.25rem    # 20px
    6: 1.5rem     # 24px
    8: 2rem       # 32px

  text:
    sm: 0.875rem  # 14px
    md: 1rem      # 16px
    lg: 1.125rem  # 18px

  color:
    surface: "#ffffff"
    surface-raised: "#fafafa"
    border: "#e5e5e5"
    text-primary: "#171717"
    text-secondary: "#525252"
    accent: "#2563eb"
    accent-hover: "#1d4ed8"
    positive: "#16a34a"
    positive-subtle: "#f0fdf4"
    positive-dark: "#15803d"
    warning: "#d97706"
    warning-subtle: "#fffbeb"
    warning-dark: "#b45309"
    critical: "#dc2626"
    critical-subtle: "#fef2f2"
    critical-dark: "#991b1b"

  shadow:
    sm: "0 1px 2px rgba(0,0,0,0.05)"
    md: "0 4px 6px rgba(0,0,0,0.1)"

  radius:
    sm: "0.25rem"
    md: "0.375rem"
    lg: "0.5rem"

# Container-centric styling
card:
  base:
    background: surface
    shadow: sm
    radius: md
  header:
    size: md
    weight: 600
    padding: 4
  body:
    padding: 4
  footer:
    padding: 4
    gap: 2
    justify: end

# Button styling
button:
  base:
    padding-x: 4
    padding-y: 2
    radius: md
    weight: 500
    size: md

  importance-primary:
    background: accent
    background-hover: accent-hover
    text: white

  importance-secondary:
    background: transparent
    border: border
    text: text-primary
    text-hover: text-primary

  importance-tertiary:
    background: transparent
    text: text-secondary
    text-hover: text-primary

  importance-ghost:
    background: transparent
    text: text-secondary
    text-hover: accent

# Text styling
text:
  base:
    size: md
    color: text-primary
    line-height: 1.5

# Form styling
input:
  base:
    padding-x: 3
    padding-y: 2
    border: border
    radius: md
    size: md
    width: 100%
  state-disabled:
    opacity: 0.5
    cursor: not-allowed

label:
  base:
    size: sm
    weight: 500
    color: text-primary
    margin-bottom: 1

field:
  base:
    gap: 1
  label:
    margin-bottom: 1
  input:
    width: 100%
  state-error:
    input:
      border-color: critical
      background: critical-subtle
  help-text:
    size: sm
    color: text-secondary
    margin-top: 1
  error-message:
    size: sm
    color: critical
    margin-top: 1

form:
  base:
    display: block

checkbox:
  base:
    size: 4  # 16px
    border: border
    radius: sm
    cursor: pointer
  checked:
    background: accent
    border-color: accent
  disabled:
    opacity: 0.5
    cursor: not-allowed

# Feedback elements
alert:
  base:
    padding-x: 4
    padding-y: 3
    radius: md
    border-width: 1
  tone-neutral:
    background: surface-raised
    border-color: border
    text: text-primary
  tone-positive:
    background: positive-subtle
    border-color: positive
    text: positive-dark
  tone-warning:
    background: warning-subtle
    border-color: warning
    text: warning-dark
  tone-critical:
    background: critical-subtle
    border-color: critical
    text: critical-dark
  message:
    size: md
    margin: 0

empty-state:
  base:
    text-align: center
    color: text-secondary
  size-small:
    padding: 3
    text-size: sm
  size-medium:
    padding: 6
    text-size: md
  size-large:
    padding: 8
    text-size: lg
  message:
    margin-bottom: 0
  action:
    margin-top: 3
    color: accent
    text-decoration: underline
